<div className="fixed inset-0 -z-50 animate-gradient bg-gradient-to-br from-[#18181b] via-[#1e293b] to-[#22c55e] opacity-80"></div>;

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BackgroundVector from "./components/BackgroundVector";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative min-h-screen w-full overflow-x-hidden">
        <BackgroundVector />
        {children}
      </body>
    </html>
  );
}
